version: "3"
services:
  server:
    build: netology-diplom-backend/
    ports:
      - "9090:9090"
  client:
    build: netology-diplom-frontend/
    ports:
      - "8081:8080"
    depends_on:
      - server
